import { Project } from './types';

export const PROJECTS_DATA: Project[] = [
  {
    id: 'proj-1',
    title: 'Chronoscape: Echoes of Aethel',
    genre: 'Sci-Fi Epic',
    description: 'In a future where humanity has colonized the stars, a renegade historian discovers a temporal anomaly that threatens to unravel reality itself.',
    notes: [
      {
        id: 'note-1-1',
        type: 'note',
        title: 'Ideas & Scratchpad',
        content: `- What if the "Helios Incident" wasn't sabotage but a natural temporal paradox Kaelen stumbled upon? Could make his obsession more tragic.\n- Rostova's backstory: Maybe the civilian casualties were on a colony world where her own family lived. This would give her a much stronger personal motivation to question the Concordance.\n- Possible names for the alien race that created the weapon: The Chronovores? The Weavers? The Architects?\n- The anomaly shouldn't just be a "hole in time." It should actively rewrite events, causing confusion and memory lapses for the characters. Imagine Kaelen and Rostova remembering different versions of the same event.`
      }
    ],
    taskLists: [
      {
        id: 'list-1-1',
        type: 'taskList',
        title: 'Drafting Goals',
        tasks: [
          { id: 't-1', text: 'Outline Chapter 1-3', isCompleted: true },
          { id: 't-2', text: 'Flesh out Kaelen\'s backstory', isCompleted: true },
          { id: 't-3', text: 'Write the inciting incident scene', isCompleted: false },
          { id: 't-4', text: 'Design the alien technology rules', isCompleted: false },
        ]
      }
    ],
    characters: [
      {
        id: 'char-1-1',
        name: 'Kaelen Vance',
        description: 'A brilliant but disgraced chronophysicist, haunted by a past failure. He is cynical but driven by a deep sense of responsibility.',
        originStory: 'Once a leading mind at the Temporal Research Institute, Kaelen was scapegoated for the "Helios Incident," a catastrophic temporal experiment that resulted in the loss of a research vessel and its crew. The official record blames his recklessness, but he knows it was a calculated sabotage by a rival.',
        familyMentors: 'Estranged from his former mentor, Dr. Aris Thorne, who publicly condemned him after the Helios Incident. Has a complicated professional rivalry with Commander Eva Rostova, whom he sees as a pawn of the bureaucratic system that ruined him.',
        secretsRegrets: 'Kaelen secretly carries a data chip with the unsanctioned logs from the Helios Incident, proof of his innocence that he cannot release without endangering his own life. His greatest regret is not speaking up about his concerns before the experiment began, a failure of courage that haunts his every waking moment.',
        relationshipsTimeline: 'Year 2451: Mentorship under Dr. Aris Thorne begins. Year 2458: The Helios Incident occurs; Kaelen is disgraced and Thorne severs all ties. Year 2460: First encounter with Commander Rostova during a fringe-world investigation.',
        storyRole: 'Protagonist, The Rebel Archetype',
        introductionPoint: 'Part I: The Anomaly, while investigating a temporal signature on Xylos.',
        arcSummary: 'Starts as a disgraced, cynical loner obsessed with redemption -> Forms an uneasy alliance with Rostova out of necessity -> Learns to trust and accepts the human cost of his work, choosing the greater good over personal vindication.',
        conflictContribution: 'Drives the central plot by discovering the anomaly and defying the Concordance. His actions create the primary external conflict with Rostova and the internal conflict of whether to trust her.',
        changeMetric: 'He learns that collaboration and trust are more powerful than isolated genius. He moves from seeking personal redemption to ensuring collective survival.',
        type: 'character',
        aliases: 'The Chrono-Ghost',
        age: '38 standard years',
        gender: 'Male',
        species: 'Human (Terran)',
        occupation: 'Fringe Scientist, former Chronophysicist',
        affiliations: 'Formerly Temporal Research Institute',
        heightBuild: 'Approx 1.8m, lean build, often hunched over consoles, moves with a restless energy.',
        faceHairEyes: 'Sharp, angular features; unruly dark hair with threads of grey; intense, deep-set grey eyes.',
        styleOutfit: 'Wears practical, often worn-out technician jumpsuits over a plain t-shirt. Always has a multi-tool clipped to his belt.',
        vocalTraits: 'Speaks quickly, often muttering complex technical jargon to himself. Voice is a low baritone, but rises when excited or agitated.',
        healthAbilities: 'Generally healthy but suffers from chronic insomnia. Possesses exceptional reflexes and problem-solving skills under pressure.',
        coreMotivation: 'To prove his theories are correct and redeem his name.',
        longTermGoal: 'To create a stable, predictable model of time travel, preventing future catastrophes.',
        fearFlaw: 'His arrogance and obsession often blind him to the human cost of his experiments. He fears another failure like the one that disgraced him.',
        moralAlignment: 'Chaotic Good. He bends rules and defies authority, but ultimately for the greater good.',
        temperament: 'Archetype: The Rebel. MBTI: INTJ (The Architect). Driven, strategic, but socially isolated.',
        emotionalTriggers: 'Being underestimated, bureaucratic red tape, and reminders of his past failure.',
        dictionSlangTone: 'Tends to use complex scientific jargon, speaks with a tone of cynical authority. Can be dismissive and abrupt.',
        gesturesHabits: 'Constantly runs a hand through his hair when stressed. Taps his fingers on any available surface while thinking. Avoids direct eye contact.',
        signaturePhrases: '"It\'s a matter of temporal mechanics, not opinion.", "The data doesn\'t lie."',
        internalThoughtStyle: 'Pragmatic and analytical, constantly running calculations and simulations in his head. His thoughts are a cascade of branching possibilities and risk assessments.',
        homeEnvironmentInfluence: 'Grew up in the sterile, academic environment of a deep-space research station, making him more comfortable with machines than people.',
        culturalReligiousBackground: 'Steeped in a culture of scientific rationalism; views metaphysics and religion with skepticism.',
        economicPoliticalStatus: 'Currently an outcast with limited resources, operating on the fringes. Politically, he is anti-authoritarian, distrusting the centralized power of the Concordance.',
        technologyMagicInteraction: 'Mastery of temporal mechanics and advanced physics. He views technology as a tool for unlocking the universe\'s fundamental secrets.',
        tiesToWorldEvents: 'Directly tied to the "Helios Incident," a significant technological disaster that shaped interstellar policy on temporal research.',
        firstLastAppearance: 'First: Part I, Xylos. Last: Part III, at the heart of the anomaly.',
        actorVisualReference: 'Think a more stressed, space-worn Oscar Isaac.',
        symbolicObjectsThemes: 'Symbolic Object: His cracked data chip (proof and burden). Theme: Redemption vs. responsibility.',
        evolutionNotes: 'Initially planned as a pure anti-hero, his arc was softened to show more vulnerability and a capacity for trust, especially with Rostova.',
        crossLinks: 'Mentioned in the "Helios Incident Report" prequel short story.',
        innerMonologueExample: '"If the decay cascade follows a standard t-minus-gamma curve, the event horizon will stabilize... but Rostova\'s fleet will be here by then. The data... is it worth more than my life? Wrong question. Is it worth more than *everyone else\'s*?"',
        playlistSoundPalette: 'Synthwave, dark ambient, the low hum of a starship engine, the crackle of a failing capacitor.',
        colorPaletteMotifs: 'Deep blues, cold greys, and the stark cyan of a holographic display. Motifs: Spirals, broken clocks.',
        aiGameReference: 'Dialogue Tree Logic: Prioritize [Sarcasm] and [Technical Explanation] options. Game Ability: "Temporal Insight" - slows time for 3 seconds to solve a puzzle.',
        developmentNotes: 'In the first draft, Kaelen was much more of a lone wolf. Feedback suggested he needed a stronger foil, which led to the expansion of Rostova\'s role and their reluctant partnership.',
      },
      {
        id: 'char-1-2',
        name: 'Commander Eva Rostova',
        description: 'A pragmatic and decorated officer of the Interstellar Concordance Fleet. She is tasked with containing the anomaly, putting her at odds with Kaelen.',
        originStory: 'Born on a disciplined military outpost, Eva rose through the ranks due to her strategic acumen and unwavering resolve. Her formative years were shaped by witnessing the chaos caused by rogue elements, instilling in her a core belief that order and control are paramount to galactic stability.',
        familyMentors: 'Reports directly to the Concordance High Council, a body she respects but is not blind to its political machinations. Sees Kaelen as a dangerous wildcard but respects his intellect enough to question her orders.',
        secretsRegrets: 'She carries the guilt of a past mission where following orders to the letter resulted in avoidable civilian casualties, a "turning point" that makes her secretly question absolute authority.',
        relationshipsTimeline: 'Maintains a professional, albeit strained, relationship with Kaelen Vance. Her career is her primary focus, leaving little room for personal connections.',
        storyRole: 'Antagonist-turned-Ally, Foil to Kaelen, The Lawful Archetype',
        introductionPoint: 'Part I: The Anomaly, arriving to quarantine the planet Xylos.',
        arcSummary: 'Starts as a rigid, by-the-book officer tasked with capturing Kaelen -> Questions her orders as she witnesses the true scale of the temporal threat -> Becomes a key ally in stopping the weapon, choosing her conscience over her career.',
        conflictContribution: 'Represents the opposing force (The Concordance) that hunts Kaelen, creating obstacles, raising the stakes, and forcing him to be more creative.',
        changeMetric: 'She learns that true order sometimes requires defying flawed authority and that morality is not always black and white.',
        type: 'character',
        dictionSlangTone: 'Formal and precise diction, using official Concordance terminology. Tone is calm, controlled, and authoritative.',
        gesturesHabits: 'Stands with a rigid, military posture. Clenches her jaw when contemplating a difficult decision. Hands are often clasped behind her back.',
        signaturePhrases: '"State your intention.", "By the authority of the Concordance...", "Order will be maintained."',
        internalThoughtStyle: 'Logical and structured, focusing on duty, protocol, and the most efficient path to mission success. Prone to weighing regulations against situational ethics.',
        homeEnvironmentInfluence: 'Raised in a structured, spartan military outpost where discipline and collective duty were prized above individuality.',
        culturalReligiousBackground: 'Adheres to the Concordance\'s secular, order-focused ideology, which functions as a civic religion for its officers.',
        economicPoliticalStatus: 'A high-ranking, respected officer within the powerful Interstellar Concordance, wielding significant political and military authority.',
        technologyMagicInteraction: 'Commands advanced military technology, from starships to tactical gear. Views it as a means to enforce stability and order.',
        tiesToWorldEvents: 'Her career has been defined by policing the fallout from events like the Helios Incident, reinforcing her belief in strict control over fringe science.',
        firstLastAppearance: 'First: Part I, arriving to quarantine Xylos. Last: Part III, defying the Concordance.',
        actorVisualReference: 'A disciplined, sharp-featured Gwendoline Christie.',
        symbolicObjectsThemes: 'Symbolic Object: Her Concordance officer\'s insignia (symbol of her duty and eventual defiance). Theme: Order vs. justice.',
        evolutionNotes: 'Her backstory of a failed mission was added to give her a stronger motivation for questioning orders, making her switch feel more earned.',
        crossLinks: 'N/A',
        innerMonologueExample: '"Regulation 4.1.7 dictates immediate containment. But Vance\'s data, however fragmented, suggests a Class-Omega threat. My duty is to the Concordance... but my responsibility is to its citizens. The two have never been in conflict before."',
        playlistSoundPalette: 'Martial orchestral music, crisp sound of marching boots, the low thrum of a warship\'s bridge.',
        colorPaletteMotifs: 'Crimson red, stark white, and polished chrome. Motifs: Straight lines, rigid geometric patterns, the Concordance insignia.',
        aiGameReference: 'AI Behavior: Patrols predefined paths until alerted. Prioritizes mission objectives over self-preservation. Will accept logical arguments if they align with a higher-priority directive.',
        developmentNotes: 'Eva was initially a much more straightforward antagonist. Making her more sympathetic and giving her a reason to doubt her orders was key to making the third act work.',
      },
    ],
    outline: [
      {
        id: 'out-1-1',
        title: 'Part I: The Anomaly',
        content: 'The story opens on the backwater planet of Xylos, where Kaelen Vance detects a strange temporal signature. He traces it to an ancient, abandoned alien structure. Inside, he finds a device that shows him fragmented visions of a collapsed timeline. Simultaneously, the Concordance Fleet, led by Commander Rostova, arrives to quarantine the planet, citing a hazardous energy surge.',
        type: 'outline',
        characterIds: ['char-1-1', 'char-1-2'],
      },
      {
        id: 'out-1-2',
        title: 'Part II: The Chase',
        content: 'Kaelen, realizing the danger is far greater than the Concordance understands, escapes the quarantine with his fragmented data. Rostova is ordered to pursue him. The chase spans several star systems, from the neon-drenched markets of Cygnus X-1 to the desolate asteroid fields of the Outer Rim. Kaelen must stay one step ahead while trying to decipher the alien data.',
        type: 'outline',
        characterIds: ['char-1-1', 'char-1-2'],
      },
       {
        id: 'out-1-3',
        title: 'Part III: Convergence',
        content: 'Kaelen discovers the anomaly is not a natural phenomenon but a weapon, created by a long-dead civilization to erase their enemies from time. The weapon is malfunctioning and threatens to consume everything. He realizes he cannot stop it alone and must convince Rostova of the true threat before it\'s too late. The climax occurs at the heart of the anomaly, where they must form an uneasy alliance to prevent total temporal collapse.',
        type: 'outline',
        characterIds: ['char-1-1', 'char-1-2'],
      },
    ],
  },
  {
    id: 'proj-2',
    title: 'The Serpent\'s Shadow',
    genre: 'Fantasy Mystery',
    description: 'In the gaslit city of Silverwood, a magically-gifted detective must solve a series of ritualistic murders tied to a forgotten dark god.',
    notes: [
      {
        id: 'note-2-1',
        type: 'note',
        title: 'Clues & Red Herrings',
        content: `- The first victim had a small, silver serpent pin on his lapel, but it was from a well-known jeweler, not the cult. (Red Herring)\n- All victims visited the same rare book shop in the week before their death. The shopkeeper is nervous and evasive. (Clue)\n- A strange, sweet-smelling incense is found at every crime scene. What is it? -> Leads to a specific black market apothecary.\n- Rumors of a 'Whispering Man' in the docks area. Is he connected or just city gossip?`
      },
      {
        id: 'note-2-2',
        type: 'note',
        title: 'Dialogue Snippets',
        content: `- Elias to Lyra: "Everyone in this city has a price, Lyra. The trick is knowing the currency. Yours is secrets. His is power. Mine... mine is just getting through the day without another ghost whispering in my ear."\n- Captain Isolde to Elias: "I don't approve of your methods, Thorne. But I can't deny your results. Just... try not to burn the city down while you're at it."`
      }
    ],
    taskLists: [],
    characters: [
      {
        id: 'char-2-1',
        name: 'Elias Thorne',
        description: 'A sharp-witted private investigator with a minor magical affinity for sensing echoes of past events. Wears a trench coat and is perpetually tired.',
        originStory: 'Exiled from the Mages\' Guild for practicing "unsanctioned methods" (psychometry), which the conservative guild feared. He now takes on cases the city watch won\'t touch, using his forbidden talents to make a living.',
        familyMentors: 'Maintains a grudging respect for Captain Isolde of the City Watch, who sees his talent but is bound by the law. Often consults with Lyra, an informant from the city\'s underbelly who provides information for a price.',
        secretsRegrets: 'He regrets the arrogance that led to his expulsion, knowing he could do more good from within the Guild. He keeps the full extent of his psychic abilities a secret, fearing both the Guild and the criminals he investigates.',
        relationshipsTimeline: 'His relationship with Lyra is purely transactional, though a thread of mutual reliance has developed over years of working together.',
        storyRole: 'Protagonist, Hardboiled Detective Archetype',
        introductionPoint: 'Chapter 1: The First Victim, hired to investigate the first murder.',
        arcSummary: 'Starts as a jaded PI working on the fringes -> Gets pulled into a conspiracy that forces him to confront his past with the Mages\' Guild -> Must use his forbidden powers to their full extent to save the city.',
        conflictContribution: 'His investigation into the murders directly opposes the cult\'s plans, making him their primary target and driving the mystery forward.',
        changeMetric: 'He learns to embrace the abilities that made him an outcast and accept his unique place in the world, moving beyond his resentment of the Guild.',
        type: 'character',
        dictionSlangTone: 'World-weary, slightly sarcastic tone. Uses some underworld slang picked up from informants, but can switch to more formal language when needed.',
        gesturesHabits: 'Often seen rubbing the bridge of his nose as if staving off a headache. Leans against walls and doorframes. A habit of looking at people from under the brim of his hat.',
        signaturePhrases: '"Every echo tells a story.", "Another lovely day in Silverwood.", "What\'s the price?"',
        internalThoughtStyle: 'Poetic and observational, notices small details others miss. His thoughts are often tinged with melancholy and a sense of history, as he pieces together echoes of the past.',
        homeEnvironmentInfluence: 'Lives in a cluttered apartment above a noisy street in Silverwood\'s less-reputable district, a setting that mirrors his own morally grey profession.',
        culturalReligiousBackground: 'Culturally, he\'s a city-dweller, familiar with both high society and the criminal underworld. Spiritually, he\'s agnostic, though his work constantly exposes him to the city\'s dark magical undercurrents.',
        economicPoliticalStatus: 'Financially precarious, living case-to-case. Politically, he is powerless, having been exiled from the influential Mages\' Guild.',
        technologyMagicInteraction: 'Possesses a rare, innate magical ability (psychometry) that is considered taboo. He interacts with magic on a personal, intuitive level, contrasting with the Guild\'s rigid, academic approach.',
        tiesToWorldEvents: 'His expulsion from the Mages\' Guild was a minor scandal in magical circles, marking a point of contention about the control of \'fringe\' magical talents.',
        firstLastAppearance: 'First: Chapter 1, at the first crime scene. Last: Final chapter, confronting the cult leader.',
        actorVisualReference: 'A younger, magically-inclined Humphrey Bogart.',
        symbolicObjectsThemes: 'Symbolic Object: His worn leather gloves (to control his psychometry). Theme: Isolation vs. connection.',
        evolutionNotes: 'His connection to the Mages\' Guild was initially just a backstory element but became central to the plot\'s resolution.',
        crossLinks: 'Appears in the short story collection "Tales from Silverwood".',
        innerMonologueExample: '"The rain in this city has a way of washing away everything but the stains. This one... this one\'s old. An echo of rage and cold, old stone. The Guild would call it a psychic contaminant. I call it a clue."',
        playlistSoundPalette: 'Smoky jazz, the sound of rain on cobblestones, a distant foghorn, quiet saxophone solos.',
        colorPaletteMotifs: 'Sepia tones, dark umber, and the occasional flash of blood red or arcane purple. Motifs: Serpents, gaslights, rain-slicked streets.',
        aiGameReference: 'Game Mechanic: "Psychic Echo". Interacting with objects reveals a ghostly vision of a past event, offering clues at the cost of "mental stability" points.',
        developmentNotes: 'Elias was originally an alchemist, but the psychometry angle felt more unique for a detective story and allowed for more visual and compelling storytelling through flashbacks/echoes.',
      },
      {
        id: 'char-2-2',
        name: 'Lyra',
        description: 'A cunning and enigmatic information broker who operates out of a hidden tavern called The Gilded Cage. Knows all the city\'s secrets.',
        originStory: 'Her origins are a mystery. She appeared in Silverwood a decade ago and quickly established herself as the go-to person for information no one else could find. Rumors say she is a former spy from a fallen kingdom.',
        familyMentors: 'She has no family or mentors to speak of, only a network of contacts built on transactions and carefully maintained leverage. She is her own master.',
        secretsRegrets: 'Her true name and past are her most guarded secrets. She regrets a betrayal in her former life that forced her to flee and create the identity of "Lyra".',
        relationshipsTimeline: 'Has a transactional but surprisingly loyal relationship with Elias Thorne, whom she finds amusingly honorable. She is feared and respected by the criminal element.',
        storyRole: 'Ally, Information Broker, Femme Fatale Archetype',
        introductionPoint: 'Chapter 2: The Whispering Cult, when Elias seeks information on the symbol.',
        arcSummary: 'Starts as a purely transactional informant -> Her own past becomes entangled in the cult\'s activities -> Must choose between self-preservation and helping Elias at great personal risk.',
        conflictContribution: 'Provides crucial information that advances the plot, but her own secrets and ambiguous loyalties create suspense and potential for betrayal.',
        changeMetric: 'She learns that connection and loyalty can be more valuable than secrets and leverage, allowing herself to trust someone for the first time in years.',
        type: 'character',
        dictionSlangTone: 'Speaks in a low, measured tone, often using metaphors and riddles. Her language is elegant but evasive.',
        gesturesHabits: 'Keeps her hands mostly still, often resting on a dagger hidden in her sleeve. Tends to watch people\'s reflections in mirrors or glasses. A subtle, knowing smile is her default expression.',
        signaturePhrases: '"A secret has its own value.", "Everything has a cost, investigator.", "Let\'s call it a professional courtesy."',
        internalThoughtStyle: 'Paranoid and strategic, constantly assessing threats and opportunities. She views conversations as chess matches, always thinking several moves ahead. Her internal monologue is a web of secrets and contingency plans.',
        homeEnvironmentInfluence: 'Operates from The Gilded Cage, a hidden tavern that is her fortress and web. The environment is one of secrets, shadows, and controlled information.',
        culturalReligiousBackground: 'A cultural chameleon, her background is deliberately obscured. She respects the power of old gods and cults as forces that can move people, but holds no personal faith.',
        economicPoliticalStatus: 'Wealthy but operates outside the formal economy. Her power is not political but based on information and leverage, making her a significant player in the city\'s underworld.',
        technologyMagicInteraction: 'She uses a network of mundane and magical means for information gathering. She is adept at using enchanted objects for communication and defense.',
        tiesToWorldEvents: 'Her backstory is hinted to be connected to the fall of a kingdom, a major past event. Her current activities are intertwined with the city\'s power struggles.',
        firstLastAppearance: 'First: Chapter 2, in The Gilded Cage. Last: Final chapter, disappearing into the city\'s shadows.',
        actorVisualReference: 'Eva Green, with a more guarded and enigmatic presence.',
        symbolicObjectsThemes: 'Symbolic Object: The Gilded Cage tavern (her fortress and prison). Theme: Secrecy vs. trust.',
        evolutionNotes: 'Planned as a potential antagonist, but her dynamic with Elias proved more interesting as a loyal, if transactional, ally.',
        crossLinks: 'Rumored to be "The Nightingale" from the "Fallen Kingdom" prequel.',
        innerMonologueExample: '"He asks for the serpent, but he doesn\'t understand the nest he\'s poking. This symbol... it smells of old blood and broken promises. The kind I left behind. Helping him is a risk. But letting this cult fester is a bigger one."',
        playlistSoundPalette: 'Trip-hop, cello suites, the clinking of glasses in a quiet bar, whispers.',
        colorPaletteMotifs: 'Emerald green, gold, and deep shadows. Motifs: Cages, keys, masks, spiderwebs.',
        aiGameReference: 'NPC Behavior: Remains in a central hub location (The Gilded Cage). Offers quests and sells information. Dialogue options with her unlock based on player reputation and discovered secrets.',
        developmentNotes: 'Lyra\'s connection to the main plot was a late addition. Originally she was just a source of information, but tying her mysterious past to the cult gave her a personal stake and a more active role.',
      },
    ],
    outline: [
      {
        id: 'out-2-1',
        title: 'Chapter 1: The First Victim',
        content: 'A high-ranking city official is found dead in his locked study, marked with a strange, serpentine symbol. The City Watch is baffled. Elias Thorne is hired by the victim\'s family to investigate discreetly. Using his powers, Elias senses a residue of dark, ancient magic at the crime scene.',
        type: 'outline',
        characterIds: ['char-2-1'],
      },
      {
        id: 'out-2-2',
        title: 'Chapter 2: The Whispering Cult',
        content: 'Elias\'s investigation leads him to Lyra, who connects the symbol to a forgotten cult that worshipped a serpent god. More bodies turn up, each murder more audacious than the last. Elias realizes the killer is following a ritualistic pattern, and the victims are all connected to a past city conspiracy.',
        type: 'outline',
        characterIds: ['char-2-1', 'char-2-2'],
      },
    ],
  },
];